#ifndef OCTCOIN_CHAINPARAMSSEEDS_H
#define OCTCOIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the octcoin network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a BIP155 serialized (networkID, addr, port) tuple.
 */
static const uint8_t chainparams_seed_main[] = {
    0x04,0x4e,0x8a,0x11,0x3d,0x21,0x6b,
};

static const uint8_t chainparams_seed_test[] = {
    0x04,0x4e,0x8a,0x11,0x3d,0x21,0x6b,
};

static const uint8_t chainparams_seed_testnet4[] = {
    0x04,0x4e,0x8a,0x11,0x3d,0x21,0x6b,
};

static const uint8_t chainparams_seed_signet[] = {
    0x04,0x4e,0x8a,0x11,0x3d,0x21,0x6b,
};
#endif // OCTCOIN_CHAINPARAMSSEEDS_H
