description "Octcoin Core Daemon"

start on runlevel [2345]
stop on starting rc RUNLEVEL=[016]

env OCTCOIND_BIN="/usr/bin/octcoind"
env OCTCOIND_USER="octcoin"
env OCTCOIND_GROUP="octcoin"
env OCTCOIND_PIDDIR="/var/run/octcoind"
# upstart can't handle variables constructed with other variables
env OCTCOIND_PIDFILE="/var/run/octcoind/octcoind.pid"
env OCTCOIND_CONFIGFILE="/etc/octcoin/octcoin.conf"
env OCTCOIND_DATADIR="/var/lib/octcoind"

expect fork

respawn
respawn limit 5 120
kill timeout 600

pre-start script
    # this will catch non-existent config files
    # octcoind will check and exit with this very warning, but it can do so
    # long after forking, leaving upstart to think everything started fine.
    # since this is a commonly encountered case on install, just check and
    # warn here.
    if ! grep -qs '^rpcpassword=' "$OCTCOIND_CONFIGFILE" ; then
        echo "ERROR: You must set a secure rpcpassword to run octcoind."
        echo "The setting must appear in $OCTCOIND_CONFIGFILE"
        echo
        echo "This password is security critical to securing wallets "
        echo "and must not be the same as the rpcuser setting."
        echo "You can generate a suitable random password using the following "
        echo "command from the shell:"
        echo
        echo "bash -c 'tr -dc a-zA-Z0-9 < /dev/urandom | head -c32 && echo'"
        echo
        echo "It is recommended that you also set alertnotify so you are "
        echo "notified of problems:"
        echo
        echo "ie: alertnotify=echo %%s | mail -s \"Octcoin Alert\"" \
            "admin@foo.com"
        echo
        exit 1
    fi

    mkdir -p "$OCTCOIND_PIDDIR"
    chmod 0755 "$OCTCOIND_PIDDIR"
    chown $OCTCOIND_USER:$OCTCOIND_GROUP "$OCTCOIND_PIDDIR"
    chown $OCTCOIND_USER:$OCTCOIND_GROUP "$OCTCOIND_CONFIGFILE"
    chmod 0660 "$OCTCOIND_CONFIGFILE"
end script

exec start-stop-daemon \
    --start \
    --pidfile "$OCTCOIND_PIDFILE" \
    --chuid $OCTCOIND_USER:$OCTCOIND_GROUP \
    --exec "$OCTCOIND_BIN" \
    -- \
    -pid="$OCTCOIND_PIDFILE" \
    -conf="$OCTCOIND_CONFIGFILE" \
    -datadir="$OCTCOIND_DATADIR" \
    -disablewallet \
    -daemon

